DROP DATABASE IF EXISTS `whats-on-stock`;
CREATE DATABASE `whats-on-stock`;
USE `whats-on-stock`;

CREATE TABLE users(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(255) NOT NULL,
	UNIQUE(email)
);

CREATE TABLE items(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	qty INT NOT NULL,
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES users(id)
);